name: CI

on:
  push:
    branches:
      - master

jobs:
  tag:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2

      - name: Tag
        id: tag
        uses: mathieudutour/github-tag-action@v4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: master
