name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2

      - name: Calculate Next Autotagging Version
        id: calc_version
        uses: mathieudutour/github-tag-action@v4.2
        with:
          dry_run: true # calculate the next version without actually tagging
          release_branches: master
