name: TAG CI

on:
  push:
    tags:
      - 'v*'

jobs:
  tag_and_build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2

      - name: Set Version
        id: new_version
        run: |
          new_version=${GITHUB_REF#"refs/tags/v"}
          echo "::set-env name=NEW_VERSION::$new_version"

      - name: Publish Docker Image
        id: docker_publish
        uses: docker/build-push-action@v1
        with:
          repository: sagebionetworks/${{ github.event.repository.name }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ env.NEW_VERSION }},latest
